### ISSUE TITLE
add link to JsonDataObjects.pas

### ISSUE THREAD

**Issue by Den2016** [staspiter/delphi-websocket#1]
Hi, Stas! 
Great library, thanks. Runs on Delphi 10.2 with google helps on JsonDataObjects.
Please, add link to readme, i`m found this on https://github.com/ahausladen/JsonDataObjects
sorry for my russian english )))

**Comment by staspiter** [comment]
Hi Denis!
The library is using JsonDataObjects as a submodule. See [these examples](https://stackoverflow.com/a/4438292) to clone repository including submodules. Glad to hear that it works alright!
