### ISSUE TITLE
How  can use the repo in other  project 

### ISSUE THREAD

**Issue by Nitinsharmapandat** [staspiter/delphi-websocket#2]
Hello  Dear sir,
      
How can I use your repo in my  Delphi repo(https://github.com/svanas/delphereum) . please help me I am facing this error in my project([dcc64 Fatal Error] web3.eth.blocknative.mempool.sgc.pas(14): F2613 Unit 'sgcWebSocket' not found.)  please tell me how can i use your repo in this project.
 please help me as soon as possible

**Comment by staspiter** [comment]
Hi,

I’m sorry, but I have to close this issue because it’s actually unrelated to the current repository. Delphi-WebSocket does not use sgcWebSocket unit.
