### ISSUE TITLE
WSS does not work with Delphi 10.2 Tokyo

### ISSUE THREAD

**Issue by giorgiobazzo** [staspiter/delphi-websocket#3]
Hi,

When I try to connect to the server using client.html, the connection to the websocket is soon closed.

Debugging the WebSocketServer.pas unit I noticed that in the line:

`TIdSSLIOHandlerSocketBase(AContext.Connection.IOHandler).PassThrough := false;`

An exception occurs: 
**'Error accepting connection with SSL. Error:1408A0C1:SSL routines:ssl3_get_client_hello:no shared cipher'**

I'm using the example from the 3-WSS folder, I edited the client.html file so that the websocket connects to wss://localhost:8080
and comment out the lines:

```
   FSSLIOHanlder.SSLOptions.CertFile := 'cert.crt';
   FSSLIOHanlder.SSLOptions.KeyFile := 'private.key';
```

because I don't have a certificate. Could that be the problem?

Is there any solution for this?

**Comment by staspiter** [comment]
Hi Giorgio,

You should set up correct certificate and private key files in order to use a secure connection. You can generate a free certificate using Let's Encrypt or ZeroSSL.
